---
version: '2'
services:
  haproxy-selfie:
    image: "anchorfree/haproxy-selfie:v0.3.4"
    container_name: haproxy-selfie
    restart: always
    environment:
      HAPROXY_HTTP_PORT: 80
      HAPROXY_HTTPS_PORT: 443
      HAPROXY_TIMEOUT_CONNECT: "5000ms"
      HAPROXY_TIMEOUT_SERVER: "5000ms"
      HAPROXY_TIMEOUT_CLIENT: "10000ms"
      HAPROXY_STATS_REFRESH_INTERVAL: 5
      HAPROXY_STATS_SOCKET_TIMEOUT: 5
      HAPROXY_STATS_SOCKET_PATH: "/var/run/haproxy.sock"
      HAPROXY_METRICS_PORT: 9101
    volumes:
    - "/etc/haproxy/conf:/etc/haproxy/conf"
    - "/etc/haproxy/user:/etc/haproxy/user"
